#!/bin/bash -e

if [ ! -h gopath/src/github.com/chrissnell/locksmith ]; then
	mkdir -p gopath/src/github.com/chrissnell/
	ln -s ../../../.. gopath/src/github.com/chrissnell/locksmith
fi

export GOBIN=${PWD}/bin
export GOPATH=${PWD}/gopath
export GO15VENDOREXPERIMENT=1

eval $(go env)

go install -ldflags "$GOLDFLAGS -extldflags -static" github.com/chrissnell/locksmith/locksmithctl
